FROM rust:1.70.0-slim AS base
WORKDIR /app
COPY ./Cargo.toml ./Cargo.lock ./
COPY ./src ./src
RUN cargo build --release

FROM rust:1.70.0-slim
COPY --from=base /app/target/release/rust-service /app/rust-service

ENTRYPOINT [ "/app/rust-service" ]